AWSTemplateFormatVersion: "2010-09-09"
Description: The EnginesService ECS Service

Parameters:
  EnvironmentName:
    Type: String
    Default: swiftx
  
  ComponentName:
    Type: String
    Default: swiftx
  
  PartName:
    Type: String
    Default: engines
  
  PrivateSubnetIds:
    Type: CommaDelimitedList
  EnginesServicePort:
    Description: EnginesService Service Port
    Type: String
    Default: 3000


  EnginesServiceSecurityGroupId:
    Description: The EnginesService security group ID
    Type: String
  EnginesServiceExecutionRoleArn:
    Description: The ARN to EnginesService IAC execution role
    Type: String
  EnginesServiceTaskRoleArn:
    Description: The ARN to EnginesService IAC task role
    Type: String
  EnginesServiceCluster:
    Description: Engines service cluster ID.
    Type: String
  ServiceImageTag:
    Type: String
    Default: latest
  ForceNewDeployment:
    Description: Force a new deployment of the ECS service
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
  IsItFirstSetup:
    Description: Boolean parameter to setup desired count
    Type: String
    Default: false
    # for autoscaling
  MinContainers:
    Type: Number
    Default: 2
  # for autoscaling
  MaxContainers:
    Type: Number
    Default: 10
  # target CPU utilization (%)
  AutoScalingTargetValue:
    Type: Number
    Default: 75

Conditions:
  ZeroDesiredCount: !Equals [!Ref IsItFirstSetup, "true"]
  NonZeroDesiredCount: !Equals [!Ref IsItFirstSetup, "false"]
  CreateProdResources:
    !Or
      - !Equals [!Ref EnvironmentName, "prod"]
      - !Equals [!Ref EnvironmentName, "prod2"]
      - !Equals [!Ref EnvironmentName, "dr"]

Resources:
  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - "-"
          - - !Ref EnvironmentName
            - !Ref ComponentName
            - !Ref PartName
            - "common-log-group"
      RetentionInDays: 365
      Tags:
        - Key: STAGE
          Value: !Ref EnvironmentName
        - Key: COMPONENT_NAME
          Value: !Ref ComponentName
        - Key: PART_NAME
          Value: !Ref PartName
        - Key: service
          Value: !Join ["-", [!Ref ComponentName, !Ref PartName]]
        - Key: StackID
          Value: !Ref "AWS::StackId"


  EnginesServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      NetworkMode: awsvpc
      Family:
        Fn::Join:
          - "-"
          - - !Ref EnvironmentName
            - !Ref ComponentName
            - !Ref PartName
            - "task-definition"
      Cpu: !If [CreateProdResources, 1024, 1024]
      Memory: !If [CreateProdResources, 2048, 2048]
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: !Sub "component-${ComponentName}-${PartName}-service-container"
          Image: !Sub
            - ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepositoryName}:${ServiceImageTag}
            - ECRRepositoryName:
                Fn::Join:
                  - "-"
                  - - !Ref EnvironmentName
                    - !Ref ComponentName
                    - !Ref PartName
                    - "ecr"
          Essential: true
          PortMappings:
            - ContainerPort: !Ref EnginesServicePort
              Protocol: tcp
          Environment:
            - Name: ENVIRONMENT_NAME
              Value: !Ref EnvironmentName
            - Name: COMPONENT_NAME
              Value: !Ref ComponentName
            - Name: PART_NAME
              Value: !Ref PartName
            - Name: AWS_REGION
              Value: !Ref AWS::Region
            - Name: PORT
              Value: !Ref EnginesServicePort
          # No Secrets section - all environment variables fetched dynamically from Parameter Store
          # ReadonlyRootFilesystem: true  # Commented out for nginx compatibility
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref CloudWatchLogsGroup
              awslogs-stream-prefix: !Join ["-", [!Ref ComponentName, !Ref PartName]]

      ExecutionRoleArn: !Ref EnginesServiceExecutionRoleArn
      TaskRoleArn: !Ref EnginesServiceTaskRoleArn
      Tags:
        - Key: STAGE
          Value: !Ref EnvironmentName
        - Key: COMPONENT_NAME
          Value: !Ref ComponentName
        - Key: PART_NAME
          Value: !Ref PartName
        - Key: service
          Value: !Join ["-", [!Ref ComponentName, !Ref PartName]]
        - Key: StackID
          Value: !Ref "AWS::StackId"
  EnginesServiceEcsService:
    Type: AWS::ECS::Service
    Properties:
      LaunchType: FARGATE
      ServiceName:
        Fn::Join:
          - "-"
          - - !Ref EnvironmentName
            - !Ref ComponentName
            - !Ref PartName
            - "ecs-service"
      Cluster: !Ref EnginesServiceCluster
      TaskDefinition: !Ref EnginesServiceTaskDefinition
      DesiredCount: !If [ZeroDesiredCount, 0, !If [CreateProdResources, 2, 1]]
      LoadBalancers:
        - ContainerName: !Sub "component-${ComponentName}-${PartName}-service-container"
          ContainerPort: !Ref EnginesServicePort
          TargetGroupArn:
            Fn::ImportValue:
              Fn::Sub:
                - "${EnginesServiceNetworkStackName}-EnginesServiceServiceTargetGroup"
                - EnginesServiceNetworkStackName:
                    Fn::Join:
                      - "-"
                      - - !Ref EnvironmentName
                        - !Ref ComponentName
                        - !Ref PartName
                        - "iac-network"
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref EnginesServiceSecurityGroupId
          Subnets: !Ref PrivateSubnetIds
      PropagateTags: TASK_DEFINITION
      HealthCheckGracePeriodSeconds: 300
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: false
          Rollback: false
      # ForceNewDeployment: !Equals 
      #   - !Ref ForceNewDeployment
      #   - "true"
      Tags:
        - Key: STAGE
          Value: !Ref EnvironmentName
        - Key: COMPONENT_NAME
          Value: !Ref ComponentName
        - Key: PART_NAME
          Value: !Ref PartName
        - Key: service
          Value: !Join ["-", [!Ref ComponentName, !Ref PartName]]
        - Key: StackID
          Value: !Ref "AWS::StackId"
  AutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Join:
          - "-"
          - - !Ref EnvironmentName
            - !Ref ComponentName
            - !Ref PartName
            - "autoscaling-role"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceAutoscaleRole"
      Tags:
        - Key: "STAGE"
          Value: !Ref EnvironmentName
        - Key: "COMPONENT_NAME"
          Value: !Ref ComponentName
        - Key: "PART_NAME"
          Value: !Ref PartName
        - Key: service
          Value: !Join ["-", [!Ref ComponentName, !Ref PartName]]
        - Key: StackID
          Value: !Ref "AWS::StackId"
  AutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: NonZeroDesiredCount
    Properties:
      MinCapacity: !If [CreateProdResources, !Ref MinContainers, 1]
      MaxCapacity: !Ref MaxContainers
      ResourceId:
        Fn::Join:
          - "/"
          - - "service"
            - !Ref EnginesServiceCluster
            - !GetAtt EnginesServiceEcsService.Name
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      # "The Amazon Resource Name (ARN) of an AWS Identity and Access Management (IAM) role that allows Application Auto Scaling to modify your scalable target."
      RoleARN: !GetAtt AutoScalingRole.Arn
  AutoScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: NonZeroDesiredCount
    Properties:
      PolicyName:
        Fn::Join:
          - "-"
          - - !Ref EnvironmentName
            - !Ref ComponentName
            - !Ref PartName
            - "autoscaling-policy"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 10
        ScaleOutCooldown: 10
        # Keep things at or lower than 50% CPU utilization, for example
        TargetValue: !Ref AutoScalingTargetValue

Outputs:
  AutoScalingRoleArn:
    Description: AutoScaling role for tms2 dd service
    Value: !GetAtt AutoScalingRole.Arn

